<?php
if(!function_exists('allianz_icons')){
	add_filter('allianz_theme_icons', 'allianz_icons');
	function allianz_icons($icons){
		$allianz_icons = [
			'Allianz Icons' => [
				["allianz-icon-default"               => "default"],
				["allianz-icon-agreement-2"           => "agreement-2"],
				["allianz-icon-agreement"             => "agreement"],
				["allianz-icon-analysis"              => "analysis"],
				["allianz-icon-analytics"             => "analytics"],
				["allianz-icon-battery"               => "battery"],
				["allianz-icon-bioengineering"        => "bioengineering"],
				["allianz-icon-business-and-finance"  => "business-and-finance"],
				["allianz-icon-document"              => "document"],
				["allianz-icon-employee-of-the-month" => "employee-of-the-month"],
				["allianz-icon-insurance-policy"      => "insurance-policy"],
				["allianz-icon-inverted-commas"       => "inverted-commas"],
				["allianz-icon-layers"                => "layers"],
				["allianz-icon-money"                 => "money"],
				["allianz-icon-open-book"             => "open-book"],
				["allianz-icon-profit-growth"         => "profit-growth"],
				["allianz-icon-profit"                => "profit"],
				["allianz-icon-quote-fill-top"        => "quote-fill-top"],
				["allianz-icon-quote-o-bot"           => "quote-o-bot"],
				["allianz-icon-quote"                 => "quote"],
				["allianz-icon-recession"             => "recession"],
				["allianz-icon-reporting"             => "reporting"],
				["allianz-icon-right-quote"           => "right-quote"],
				["allianz-icon-risk-management"       => "risk-management"],
				["allianz-icon-room-service"          => "room-service"],
				["allianz-icon-team-management"       => "team-management"],
				["allianz-icon-work-team"             => "work-team"],
				["allianz-icon-question-and-answer"   => "question-and-answer"],
				["allianz-icon-knowledge"             => "knowledge"],
				["allianz-icon-expert"                => "expert"],
				["allianz-icon-help"                  => "help"],
				["allianz-icon-strategy"              => "strategy"],
				["allianz-icon-ideas"                 => "ideas"],
				["allianz-icon-advice"                => "advice"],
				["allianz-icon-Partnership-handshake" => "Partnership-handshake"],
				["allianz-icon-idea"                  => "idea"],
				["allianz-icon-human-resources"       => "human-resources"],
				["allianz-icon-goal"                  => "goal"],
				["allianz-icon-report"                => "report"],
				["allianz-icon-help1"                 => "help1"],
				["allianz-icon-financial-consultant"  => "financial-consultant"],
				["allianz-icon-networking"            => "networking"],
				["allianz-icon-consultant"            => "consultant"],
				["allianz-icon-financial-profit"      => "financial-profit"],
				["allianz-icon-management"            => "management"],
				["allianz-icon-Successful"            => "Successful"],
				["allianz-icon-help2"                 => "help2"],
				["allianz-icon-risk"                  => "risk"],
				["allianz-icon-customer-support"      => "customer-support"],
				["allianz-icon-research"              => "research"],
				["allianz-icon-checklist"             => "checklist"],
				["allianz-icon-expert1"               => "expert1"],
				["allianz-icon-swot-analysis"         => "swot-analysis"],
				["allianz-icon-safety"                => "safety"],
				["allianz-icon-consultant1"           => "consultant1"],
				["allianz-icon-idea1"                 => "idea1"],
				["allianz-icon-solution"              => "solution"],
				["allianz-icon-evaluation"            => "evaluation"],
				["allianz-icon-science"               => "science"],
				["allianz-icon-consultancy"           => "consultancy"],
				["allianz-icon-backlog"               => "backlog"],
				["allianz-icon-business-meeting"      => "business-meeting"],
				["allianz-icon-valuable"              => "valuable"],
				["allianz-icon-customer-support1"     => "customer-support1"],
				["allianz-icon-diagnosis"             => "diagnosis"],
				["allianz-icon-analysis1"             => "analysis1"],
				["allianz-icon-question-and-answer1"  => "question-and-answer1"],
				["allianz-icon-consultant2"           => "consultant2"],
				["allianz-icon-consultancy1"          => "consultancy1"],
				["allianz-icon-global"                => "global"],
				["allianz-icon-decision-making"       => "decision-making"],
				["allianz-icon-market-analysis"       => "market-analysis"],
				["allianz-icon-video-call"            => "video-call"],
				["allianz-icon-advice1"               => "advice1"],
				["allianz-icon-advanced-training"     => "advanced-training"],
				["allianz-icon-marketing"             => "marketing"],
				["allianz-icon-risk-management1"      => "risk-management1"],
				["allianz-icon-up-right-arrow"        => "up-right-arrow"],
				["allianz-icon-left-arrow"            => "left-arrow"],
				["allianz-icon-right-arrow"           => "right-arrow"],
				["allianz-icon-business-plan"         => "business-plan"],
				["allianz-icon-research-2"            => "research-2"],
				["allianz-icon-taxes"                 => "taxes"],
				["allianz-icon-cart"                  => "cart"]
			]
		];
		return array_merge($icons, $allianz_icons);
	}
}